apiVersion: v1
kind: Service
metadata:
  name: admin-tool-nodeport
  namespace: nsready-tier2
spec:
  type: NodePort
  selector:
    app: admin-tool
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32002








