apiVersion: v1
kind: Service
metadata:
  name: collector-nodeport
  namespace: nsready-tier2
spec:
  type: NodePort
  selector:
    app: collector-service
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 32001
