apiVersion: v1
kind: Service
metadata:
  name: nats-monitor-nodeport
  namespace: nsready-tier2
spec:
  type: NodePort
  selector:
    app: nats
  ports:
    - port: 8222
      targetPort: 8222
      nodePort: 32022








