apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: nsready-tier2
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32090
  selector:
    app: prometheus








