apiVersion: v1
kind: Secret
metadata:
  name: nsready-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  JWT_ISSUER: {{ .Values.secrets.jwtIssuer }}
  NATS_TOKEN: {{ .Values.secrets.natsToken }}


